<div class="container main">
  <h2>ಪ್ರವಚನಗಳ ವೀಡಿಯೊಗಳು</h2><br />
  <div class="row videoCovers text-center">
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/RtQXPPhTGV8"><img src="<?=PUBLIC_URL?>images/stock/video-covers/001.jpg" alt="" /><p class="pravachanaTitle">Kannada Song On Essence Of Vedantha</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/TmsRhWs81oU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/002.jpg" alt="" /><p class="pravachanaTitle">Adbhuta Shankara - Shankara Jayanthi Special Lecture</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/fsBJuQTVFHc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/003.jpg" alt="" /><p class="pravachanaTitle">Adiyakaanade Arasi Balalide</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/Ao8cCfVBrpI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/004.jpg" alt="" /><p class="pravachanaTitle">Mareyadiro Maanavane</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/rzFMojQ19eA"><img src="<?=PUBLIC_URL?>images/stock/video-covers/005.jpg" alt="" /><p class="pravachanaTitle">Chaandogya Upanishat</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/VC7QUUMwvbs"><img src="<?=PUBLIC_URL?>images/stock/video-covers/006.jpg" alt="" /><p class="pravachanaTitle">Taittireeya Upanishat (krishnayajurvedeeya)</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/USrCP7xuO-w"><img src="<?=PUBLIC_URL?>images/stock/video-covers/007.jpg" alt="" /><p class="pravachanaTitle">Shravanada Mahatva</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/2RwQdNSgPWc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/008.jpg" alt="" /><p class="pravachanaTitle">Brahmajnaanada Mahime</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/LIMsTBG1jXs"><img src="<?=PUBLIC_URL?>images/stock/video-covers/009.jpg" alt="" /><p class="pravachanaTitle">Vidye Avidye &amp; Bhajans By H. H. Swamiji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/32aMJvkn2hM"><img src="<?=PUBLIC_URL?>images/stock/video-covers/010.jpg" alt="TBD" /><p class="pravachanaTitle">Advaitavu Mathavalla- Bold Voice Of H.h.swamiji In 1972</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/1DIctNmpss0"><img src="<?=PUBLIC_URL?>images/stock/video-covers/011.jpg" alt="TBD" /><p class="pravachanaTitle">Vyvahaara Endarenu, Voice Of H H Satchidaanandendra Saraswathi Swamiji Of Holenarasipur</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/D_j18JUvWOc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/012.jpg" alt="TBD" /><p class="pravachanaTitle">Sampradaya Endarenu  Voice Of H H Satchidanandendra Saraswathi Swamiji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/IkYNSYQBcqI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/013.jpg" alt="TBD" /><p class="pravachanaTitle">Sadguru Charanake Baagi</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/YCI9csGcOxQ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/014.jpg" alt="TBD" /><p class="pravachanaTitle">Hare Rama Hare Swamiji Song</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/fefmkoMQBcw"><img src="<?=PUBLIC_URL?>images/stock/video-covers/015.jpg" alt="TBD" /><p class="pravachanaTitle">S Putta Shamanna Voice</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/eHygejqZyPk"><img src="<?=PUBLIC_URL?>images/stock/video-covers/016.jpg" alt="TBD" /><p class="pravachanaTitle">Upanishat Endarenu H H Sawamiji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/YOBW5cQs4wM"><img src="<?=PUBLIC_URL?>images/stock/video-covers/017.jpg" alt="TBD" /><p class="pravachanaTitle">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 03</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/PKHcE37xBQc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/018.jpg" alt="TBD" /><p class="pravachanaTitle">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 02</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/ANRc2MuiqrI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/019.jpg" alt="TBD" /><p class="pravachanaTitle">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 01</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/RoDmoDqaqhY"><img src="<?=PUBLIC_URL?>images/stock/video-covers/020.jpg" alt="TBD" /><p class="pravachanaTitle">Soundarya Lahari In 100 Raaga's</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/7pt-xfoPesg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/021.jpg" alt="TBD" /><p class="pravachanaTitle">Satyave Gedditu Song  Real Independence Day</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/pYHCLaNRBgc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/022.jpg" alt="TBD" /><p class="pravachanaTitle">Ishavasya Upanishad Sara In Kaannada Upanyasa By Dr K G Subraya Sharma</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/NR8iwkhLtZU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/023.jpg" alt="TBD" /><p class="pravachanaTitle">Dashopanishat Teaching For Learners</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/jNxLLnC3F6o"><img src="<?=PUBLIC_URL?>images/stock/video-covers/024.jpg" alt="TBD" /><p class="pravachanaTitle">Dashopanishat Main Mantras Teaching 0001</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/rpuNPsu_anU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/025.jpg" alt="TBD" /><p class="pravachanaTitle">Kannada Lecture On Vyasa Purnima &amp; Guru Ashtaka Of Shankaracharya, By Dr K G Subraya Sharma</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/I4j1kYqOhcM"><img src="<?=PUBLIC_URL?>images/stock/video-covers/026.jpg" alt="TBD" /><p class="pravachanaTitle">Viveka Choodamani Upanyasa By Mahamahopaadhyaaya Dr K.g.subraya Sharmaji In   Kannada</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/kMtnEAqIB1g"><img src="<?=PUBLIC_URL?>images/stock/video-covers/027.jpg" alt="TBD" /><p class="pravachanaTitle">Viveka In Taittireeya</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/OxF_3Ian7Xo"><img src="<?=PUBLIC_URL?>images/stock/video-covers/028.jpg" alt="TBD" /><p class="pravachanaTitle">Janivaarada Mahatva Dr K G Subraya Sharma</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/HiJuSkYYoag"><img src="<?=PUBLIC_URL?>images/stock/video-covers/029.jpg" alt="TBD" /><p class="pravachanaTitle">ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol - 2  ಅಂದರೆ -  ಇಂದು ವೇದಾಂತ ಬೇಕೇ?, ಕೇಳಿ........ ನೀವೇ ಉತ್ತರ ಕಂಡು ಹಿಡಿಯಿರಿ.</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/MCWysMOAPg8"><img src="<?=PUBLIC_URL?>images/stock/video-covers/030.jpg" alt="TBD" /><p class="pravachanaTitle">Namage Indu Vedaantha Beke ? ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol.-1</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/0GXKfaNS6jY"><img src="<?=PUBLIC_URL?>images/stock/video-covers/031.jpg" alt="TBD" /><p class="pravachanaTitle">Brahmakkoo Ninagoo Bhedavilla</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/PwkVg3oX3QI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/032.jpg" alt="TBD" /><p class="pravachanaTitle">Dhanya Naanaadenu</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/V9C9P1lgVOI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/033.jpg" alt="TBD" /><p class="pravachanaTitle">Mayapaashada Bandhade Baride</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/wEn2GBUKrlg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/034.jpg" alt="TBD" /><p class="pravachanaTitle">Rama Rama Rama Enniri</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/UVF1bNRTB30"><img src="<?=PUBLIC_URL?>images/stock/video-covers/035.jpg" alt="TBD" /><p class="pravachanaTitle">Mandukya Upanishad Sara In Kannada</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/b-4l-Cu5tKk"><img src="<?=PUBLIC_URL?>images/stock/video-covers/036.jpg" alt="TBD" /><p class="pravachanaTitle">Shrimad Bhagavdgita Lecture In English By Dr.k.g.subraya Sharmaji At Iiwc</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/YwlYqf0VmLQ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/037.jpg" alt="TBD" /><p class="pravachanaTitle">Sri Srigala Aaradhane Kannada  Shankara</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/UQxfzn7Xvwk"><img src="<?=PUBLIC_URL?>images/stock/video-covers/038.jpg" alt="TBD" /><p class="pravachanaTitle">Shankara Hridayam, Sanskrit Lecture By Mahamahopaadhyaya Dr K G Subraya Sharma 0001</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/peCdOBRQLKI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/039.jpg" alt="TBD" /><p class="pravachanaTitle">Jist Of Shantimantras In English By Mahamahopadhyaya Dr.k.g.subraya Sharmaji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/Ly8zu-Ck6UA"><img src="<?=PUBLIC_URL?>images/stock/video-covers/040.jpg" alt="TBD" /><p class="pravachanaTitle">N H S Prayer</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/0rMVSYYxfO8"><img src="<?=PUBLIC_URL?>images/stock/video-covers/041.jpg" alt="TBD" /><p class="pravachanaTitle">Mandookya Rahasya Vivruthihi</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/x_vZP2CbKvI"><img src="<?=PUBLIC_URL?>images/stock/video-covers/042.jpg" alt="TBD" /><p class="pravachanaTitle">Bhagavadgeetha  Yaarige ? (saara)  Upanyasa K G Subraya Sharmaji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/kCV_WHVgY80"><img src="<?=PUBLIC_URL?>images/stock/video-covers/043.jpg" alt="TBD" /><p class="pravachanaTitle">Aatmahatye Endarenu ? H H Satchidaanandendra Saraswathi Of Holenarasipur Lecture</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/4N3Lwx2KoyU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/044.jpg" alt="TBD" /><p class="pravachanaTitle">Avasthatraya Prakriya By Dr.k.g.subraya Sharmaji</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/bT6Kl_kpnV0"><img src="<?=PUBLIC_URL?>images/stock/video-covers/045.jpg" alt="TBD" /><p class="pravachanaTitle">5 Mundakopanishat Saara</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/uDxj03l9NT0"><img src="<?=PUBLIC_URL?>images/stock/video-covers/046.jpg" alt="TBD" /><p class="pravachanaTitle">7 Aitareya Upanishat Saara</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/CCa4FvVv2gk"><img src="<?=PUBLIC_URL?>images/stock/video-covers/047.jpg" alt="TBD" /><p class="pravachanaTitle">4 Prashnopanishat Saara</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/O83kF5VBFgo"><img src="<?=PUBLIC_URL?>images/stock/video-covers/048.jpg" alt="TBD" /><p class="pravachanaTitle">3 Kathopanishat Saara Kannada Lecture</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/9zEDi6ClkBU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/049.jpg" alt="TBD" /><p class="pravachanaTitle">Vyasa Poornima</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/Sm6maQCOYTY"><img src="<?=PUBLIC_URL?>images/stock/video-covers/050.jpg" alt="TBD" /><p class="pravachanaTitle">Bhagavatpaada Shankaracharya</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/kjxIJ1lMmJE"><img src="<?=PUBLIC_URL?>images/stock/video-covers/051.jpg" alt="TBD" /><p class="pravachanaTitle">Vedantha Darshana</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/ziTLaVZMzH4"><img src="<?=PUBLIC_URL?>images/stock/video-covers/052.jpg" alt="TBD" /><p class="pravachanaTitle">Mayapaashada</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/k1kJiex-VZg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/053.jpg" alt="TBD" /><p class="pravachanaTitle">Elu Jeevara Jeeva</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/osCOWZDVA9s"><img src="<?=PUBLIC_URL?>images/stock/video-covers/054.jpg" alt="TBD" /><p class="pravachanaTitle">2 Kenopanishat  Saara, ಕೇನೋಪನಿಶತ್ ಉಪನ್ಯಾಸ</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/hRY8MAY9pNc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/055.jpg" alt="TBD" /><p class="pravachanaTitle">1 Eeshavaasya Upanishat Saara</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/nZ0JFCvfxTM"><img src="<?=PUBLIC_URL?>images/stock/video-covers/056.jpg" alt="TBD" /><p class="pravachanaTitle">Rama Rama Rama  Enniri</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/ENECw2RnWFk"><img src="<?=PUBLIC_URL?>images/stock/video-covers/057.jpg" alt="TBD" /><p class="pravachanaTitle">Kaalanaatavaa Nodi</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/NRWt-B-Byfw"><img src="<?=PUBLIC_URL?>images/stock/video-covers/058.jpg" alt="TBD" /><p class="pravachanaTitle">Adhyaaropaapavada Prakriya Upanyasa In Sanskrit By Mahaamahopaadhyaya Dr.k.g.subraya Sharmaji,</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/iOjlPhHQXVg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/059.jpg" alt="TBD" /><p class="pravachanaTitle">Karunisute Nee Kaaye</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/wEIKJRLQLxc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/060.jpg" alt="TBD" /><p class="pravachanaTitle">Nodutaliruvenu Naanellaa 0002</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/sMwwPeek2RM"><img src="<?=PUBLIC_URL?>images/stock/video-covers/061.jpg" alt="TBD" /><p class="pravachanaTitle">Naane Brahmavu Berallaa</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/a3X1kjpnKZg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/062.jpg" alt="TBD" /><p class="pravachanaTitle">Anjaneya Vandipenayya</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/eOjxkR3nHH4"><img src="<?=PUBLIC_URL?>images/stock/video-covers/063.jpg" alt="TBD" /><p class="pravachanaTitle">Banniri Bhajaneya Maadona</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/DCyMf1Nskcg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/064.jpg" alt="TBD" /><p class="pravachanaTitle">K Subramanya Shastriji - Poulastya Brahmana Drama</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/wFXmojxoJq0"><img src="<?=PUBLIC_URL?>images/stock/video-covers/065.jpg" alt="TBD" /><p class="pravachanaTitle">Sharanu Shankara 0001</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/-NcCpzF0FbE"><img src="<?=PUBLIC_URL?>images/stock/video-covers/066.jpg" alt="TBD" /><p class="pravachanaTitle">Shiva Shiva  Song</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/0azekaWGj0Y"><img src="<?=PUBLIC_URL?>images/stock/video-covers/067.jpg" alt="TBD" /><p class="pravachanaTitle">Sooryanamaskaara Mantra- Ratha Saptami,</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/oHpQCc0GWHQ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/068.jpg" alt="TBD" /><p class="pravachanaTitle">Sullina Jagavidu  Sung By Sanjeeva Murthy</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/MjdGyPC_S6Y"><img src="<?=PUBLIC_URL?>images/stock/video-covers/069.jpg" alt="TBD" /><p class="pravachanaTitle">Sadguru Charanake Sanjeeva Murthy</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/s4VGPTQJ-OU"><img src="<?=PUBLIC_URL?>images/stock/video-covers/070.jpg" alt="TBD" /><p class="pravachanaTitle">Dayamaado Deva, Sung By  Chitradurga Sanjeeva Murthy</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/7iRqvjve5EE"><img src="<?=PUBLIC_URL?>images/stock/video-covers/071.jpg" alt="TBD" /><p class="pravachanaTitle">Nelanolenitho Mandi Gurugalu</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/K85xd30wtyQ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/072.jpg" alt="TBD" /><p class="pravachanaTitle">Sakkadave Bekemba</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/RJQqjvcGqRg"><img src="<?=PUBLIC_URL?>images/stock/video-covers/073.jpg" alt="TBD" /><p class="pravachanaTitle">Ganesha Song With Vedanta By Sri. K.subramanya Shastry</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/Fy0ZzlQmebY"><img src="<?=PUBLIC_URL?>images/stock/video-covers/074.jpg" alt="TBD" /><p class="pravachanaTitle">6 Maandukya Upanishat</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/Q7ukl4eBuPw"><img src="<?=PUBLIC_URL?>images/stock/video-covers/075.jpg" alt="TBD" /><p class="pravachanaTitle">Naada Naada - Sung By Sanjeeva Murthy</p></a></div>
    <div class="col-md-3 video"><a href="<?=BASE_URL?>pravachana/videoPlayer/ERgKn8s7RFQ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/076.jpg" alt="TBD" /><p class="pravachanaTitle">Naada Sung by Sanjeeva Murthy 3 Gelavu , Biduvanendige</p></a></div>
  </div>
</div>